### ISSUE TITLE
Route Index Misconstruction on Controller Generation

### ISSUE THREAD

**Issue by elishaukpong** [mshamaseen/laravel-repository-pattern#3]
On line 16 in controller stub file,  it has this line of code:
 `protected $routeIndex = '{{lcPluralModelName}}.index';`
on repository generation, say, to generate for Products, this line of code is run on the terminal
`php artisan make:repository Products\\Product` 
the generated controller has this line of code:
 `protected $routeIndex = 'products.index';`

the issue here is that, on creating a model, it uses this $routeIndex for redirection, and it throws an error, as the make response function in the base controller expects a path but recieves a route name.

` return Redirect::to($this->routeIndex)->with('message', __('repository-generator.success'));`

I think the controller stub should be refactored to 
`protected $routeIndex = '{{lcPluralModelName}}/index';`

**Comment by mshamaseen** [comment]
@Drumzminister issue fixed in tag number 0.5.3
